### ISSUE TITLE
Querqy (solr) 5.1 bug - not possible to backup collection when rewriter handler configred without rewriters

### ISSUE THREAD

**Issue by jaceq** [querqy/querqy#245]
Versions:
Querqy 5.1
Solr 8.9.0

I found that if rewriter handler is configured:

`<requestHandler name="/querqy/rewriter" class="querqy.solr.QuerqyRewriterRequestHandler"/>
`

But no rewriters are configured via above endpoint, a collection backup call, eg:

`http://127.0.0.1:8983/solr/admin/collections?action=BACKUP&collection=some_collection_name&name=some_backup_name&incremental=false&repository=local&location=/tmp`

will fail with NPE:

`"org.apache.solr.common.SolrException\n\tat org.apache.solr.client.solrj.SolrResponse.getException(SolrResponse.java:65)\n\tat org.apache.solr.handler.admin.CollectionsHandler.invokeAction(CollectionsHandler.java:301)\n\tat org.apache.solr.handler.admin.CollectionsHandler.handleRequestBody(CollectionsHandler.java:257)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)\n\tat org.apache.solr.servlet.HttpSolrCall.handleAdmin(HttpSolrCall.java:836)\n\tat org.apache.solr.servlet.HttpSolrCall.handleAdminRequest(HttpSolrCall.java:800)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:545)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:357)\n\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)\n\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)\n\tat org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)\n\tat org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)\n\tat org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)\n\tat org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)\n\tat org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:177)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:322)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:516)\n\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)\n\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)\n\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)\n\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)\n\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)\n\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)\n\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"`

Interestingly, when this NPE error is given, actual backup is performed (but I am not sure if it's complete) and can be found in given destination directory.

A workaround is to add any rewriter via this endpoint and issue the backup call again.

**Comment by Paul-Blanchaert** [comment]
@renekrie 
Also encountered this issue. 
The backup is not complete as the NPE occurs in the ZK config backup stage. 
Hence, index data is stored, but zk config backup is incomplete and index backup properties are not writen. So LISTBACKUP command doesn't show the backup.

**Comment by renekrie** [comment]
@Paul-Blanchaert Would you have any further log messages? Looking at the stacktrace in the original post, I cannot spot anything related to the backup (it looks just like general request handling)

**Comment by Paul-Blanchaert** [comment]
@renekrie 
I've looked into this problem in a test setup... 
The root cause for the backup to fail is the empty .data node in zookeeper that is created upon startup of the querqy request handler in solr.

Attached is the full debug log of the backup...
[solr-backup-error.log](https://github.com/querqy/querqy/files/11982203/solr-backup-error.log)

Error:
2023-07-07 12:33:52.121 DEBUG (OverseerThreadFactory-17-thread-3) [c:gettingstarted_20230707] o.a.s.c.b.BackupManager **Writing file querqy/rewriters/.data**
2023-07-07 12:33:52.123 ERROR (OverseerThreadFactory-17-thread-3) [c:gettingstarted_20230707] o.a.s.c.a.c.OverseerCollectionMessageHandler Collection: gettingstarted_20230707 operation: backup failed => java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null
	at java.base/java.io.OutputStream.write(Unknown Source)
java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null
	at java.io.OutputStream.write(Unknown Source) ~[?:?]
	at org.apache.solr.core.backup.BackupManager.downloadConfigToRepo(BackupManager.java:349) ~[?:?]
	at org.apache.solr.core.backup.BackupManager.downloadConfigDir(BackupManager.java:276) ~[?:?]
	at org.apache.solr.cloud.api.collections.BackupCmd.call(BackupCmd.java:149) ~[?:?]
	at org.apache.solr.cloud.api.collections.OverseerCollectionMessageHandler.processMessage(OverseerCollectionMessageHandler.java:126) ~[?:?]
	at org.apache.solr.cloud.OverseerTaskProcessor$Runner.run(OverseerTaskProcessor.java:566) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:289) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

It basically is a solr issue that is not dealing well with empty zookeeper nodes...
Note:
- when I create an empty file (with touch) and copy it in zookeeper (with "solr zk cp"), the backup doesn't raise the error (and backup succeeds).
- when I create an empty node in zookeeper (via zkCli.sh session and "create" command), the backup raises the same error.

I'll raise an issue in Solr to see if they want to sort this out.
However, querqy request handler might also postpone the creation of the .data node until an actual rewriter is saved.

**Comment by renekrie** [comment]
Thank you! I now remember that we made the ZK storage path for Querqy configurable: https://querqy.org/docs/querqy/solr-plugin-configuration.html#configuring-how-rewriter-definitions-are-stored-in-zookeeper-querqy-5 (this also helps with the restoration of the backup in Solr as .data would get ignored)

**Comment by Paul-Blanchaert** [comment]
@renekrie 
FYI
[SOLR-16877](https://issues.apache.org/jira/browse/SOLR-16877) has been fixed for 9.3!
re the name of the dir:  
I tried the empty node problem with different file names (with and without a leading dot), and both raised the issue.
It is however a good tip about the data dir renaming in order to enable the restore of the rewriters.

**Comment by renekrie** [comment]
Excellent - thank you!
