### ISSUE TITLE
Querqy does not tolerate nested quotation marks in it's query parser

### ISSUE THREAD

**Issue by pan-daniel** [querqy/querqy#602]
## Description

We had a situation using SMUI, where product manager has input a phrase like "MacBook Pro 16" M3". 
This has caused Solr to throw errors around, forcing our Kubernetes to try and restart it.

## Expected behaviour:

Querqy can tolerate both nested `"MacBook Pro 16" M3"` and single quotation marks, like `MacBook Pro 16" M3`.

## Stack trace

```java
org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Syntax error
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:217)
	at querqy.solr.QuerqyQueryComponent.prepare(QuerqyQueryComponent.java:44)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:389)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:224)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2893)
	at org.apache.solr.servlet.HttpSolrCall.executeCoreRequest(HttpSolrCall.java:871)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:567)
	at org.apache.solr.servlet.SolrDispatchFilter.dispatch(SolrDispatchFilter.java:250)
	at org.apache.solr.servlet.SolrDispatchFilter.lambda$doFilter$0(SolrDispatchFilter.java:218)
	at org.apache.solr.servlet.ServletUtils.traceHttpRequestExecution2(ServletUtils.java:257)
	at org.apache.solr.servlet.ServletUtils.rateLimitRequest(ServletUtils.java:227)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:213)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:313)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:267)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.InetAccessHandler.handle(InetAccessHandler.java:228)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:301)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:457)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.solr.search.SyntaxError: Syntax error
	at querqy.solr.QuerqyDismaxQParser.parse(QuerqyDismaxQParser.java:94)
	at querqy.solr.QuerqyDismaxQParser.getQuery(QuerqyDismaxQParser.java:104)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:171)
	... 63 more
Caused by: querqy.lucene.LuceneSearchEngineRequestAdapter$SyntaxException: org.apache.solr.search.SyntaxError: Cannot parse 'nameWithoutManufacturer:"MacBook Pro 16" M3"': Lexical error at line 1, column 45.  Encountered: <EOF> (in lexical state 3)
	at querqy.solr.DismaxSearchEngineRequestAdapter.parseRawQuery(DismaxSearchEngineRequestAdapter.java:321)
	at querqy.lucene.QueryParsingController.transformAdditiveBoostQueries(QueryParsingController.java:371)
	at querqy.lucene.QueryParsingController.getAdditiveQuerqyBoostQueries(QueryParsingController.java:337)
	at querqy.lucene.QueryParsingController.process(QueryParsingController.java:208)
	at querqy.solr.QuerqyDismaxQParser.parse(QuerqyDismaxQParser.java:89)
	... 65 more
Caused by: org.apache.solr.search.SyntaxError: Cannot parse 'nameWithoutManufacturer:"MacBook Pro 16" M3"': Lexical error at line 1, column 45.  Encountered: <EOF> (in lexical state 3)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:277)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:51)
	at org.apache.solr.search.QParser.getQuery(QParser.java:188)
	at querqy.solr.DismaxSearchEngineRequestAdapter.parseRawQuery(DismaxSearchEngineRequestAdapter.java:297)
	... 69 more
Caused by: org.apache.solr.parser.TokenMgrError: Lexical error at line 1, column 45.  Encountered: <EOF> (in lexical state 3)
	at org.apache.solr.parser.QueryParserTokenManager.getNextToken(QueryParserTokenManager.java:1503)
	at org.apache.solr.parser.QueryParser.getToken(QueryParser.java:876)
	at org.apache.solr.parser.QueryParser.jj_3R_MultiTerm_329_3_3(QueryParser.java:714)
	at org.apache.solr.parser.QueryParser.jj_3_2(QueryParser.java:675)
	at org.apache.solr.parser.QueryParser.jj_2_2(QueryParser.java:660)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:211)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:143)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:274)
	... 72 more
```

**Comment by renekrie** [comment]
Thank you for reporting it @pan-daniel ! I think with "single quotation mark" you mean a single double quote in the middle of the rule input? (so `abc " def` doesn't work but you didn't mean the actual single quote character like in `abc ' def`?)

I'm not sure whether we ever implemented  a way to escape the `"` character, we actually might have an option to just make it `\"`  - I will have to check.

**Comment by pan-daniel** [comment]
Yes, precisely, it is only about the `"` character.

**Comment by renekrie** [comment]
I'm realising only on second glance that the issue does not exist in the declaration of the input to the rule (in the common rules rewriter) but in a Lucene "raw" query in the right hand side part of the rule declaration.
The problem at this point is that the rewriter operates at the `querqy-core` level, which means that it doesn't "know" about Lucene at all and thus cannot validate the rule ('raw queries' - those prefixed with `*`-  are a 'blackbox' for querqy-core).

On a positive note, this also means that you can already prevent the problem by validating the Lucene query syntax on your own - there already is a way to escape `"` in Lucene, escaping is nothing we need to provide in Querqy.

In order to validate "raw" queries in Querqy, we could use an abstraction of a `RawQueryValidator` in `querqy-core` and configure the specific implementation for Lucene in the Rewriter configuration. Invalid rules (= the entire configuration) would then be rejected when the configuration is pushed to Solr/ES/OS.
