### ISSUE TITLE
querqy-solr tests sometimes fail due to random locale

### ISSUE THREAD

**Issue by renekrie** [querqy/querqy#80]
Using the Solr testing framework, tests sometimes fail. It seems that this is triggered by some random locale chosen by the framework. One such locale is `tr-CY`, so 

`mvn test -Dtests.locale=tr-CY`

always fails. Example error:

```
[ERROR] testThatOptCanBePassedAsBoostMethodParam(querqy.solr.BoostMethodTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.RuntimeException: org.apache.solr.core.SolrCoreInitializationException: SolrCore 'collection1' is not available due to init failure: querqy.rewrite.commonrules.RuleParseException: Line 2: @ expected at beginning of line: FILTER: * f2:c
	at querqy.solr.BoostMethodTest.setUp(BoostMethodTest.java:37)
Caused by: org.apache.solr.core.SolrCoreInitializationException: SolrCore 'collection1' is not available due to init failure: querqy.rewrite.commonrules.RuleParseException: Line 2: @ expected at beginning of line: FILTER: * f2:c
	at querqy.solr.BoostMethodTest.setUp(BoostMethodTest.java:37)
```

**Comment by renekrie** [comment]
This is partly due to an issue in JsonPath, PR submitted https://github.com/json-path/JsonPath/pull/601.

We have a similar issue in `querqy.rewrite.commonrules.LineParser`. I'm going to submit a fix for it.
